---
services:
  bert:
    container_name: bert
    build: bot
    image: karsten.zip/bert
    env_file:
      - .env
      - bot.env
    volumes:
      - ./bot/sounds:/usr/src/app/sounds
    depends_on:
      lavalink:
        condition: service_healthy
    restart: unless-stopped

  website:
    container_name: bert-website
    build: website
    image: karsten.zip/bertsite
    ports:
      - "6969:3000"
    env_file:
      - .env
      - website.env
    environment:
      NUXT_DISCORD_BOT_TOKEN: ${BOT_TOKEN}
      NUXT_PUBLIC_SUPABASE_URL: ${SUPABASE_URL}
    restart: unless-stopped

  lavalink:
    container_name: bert-lavalink
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    healthcheck:
      test: nc -z localhost 2333
      start_period: 3s
      interval: 2s
      timeout: 2s
      retries: 5
    env_file:
      - .env
    environment:
      - _JAVA_OPTIONS=-Xmx3G
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD}
      - PLUGINS_YOUTUBE_OAUTH_REFRESH_TOKEN=${YT_REFRESH_TOKEN}
    volumes:
      - ./lavalink.yml:/opt/Lavalink/application.yml
      - ./bot/sounds:/opt/Lavalink/sounds
    restart: unless-stopped
